// siteText.js
export const siteText = [
  { page: '/home', text: 'Welcome to our homepage. The U.S. Department of Energy’s four Power Marketing Administrations are responsible for selling the electrical output from federally owned and operated hydroelectric dams. Together, the reach of these four Power Marketing Administrations — Bonneville Power Administration, Southeastern Power Administration, Southwestern Power Administration, and Western Area Power Administration — spans 34 states and supplies power to various regions throughout the country.One of NNSA’s core missions is to ensure the United States maintains a safe, secure, and reliable nuclear stockpile through the application of unparalleled science, technology, engineering, and manufacturing. The Office of Defense Programs carries out NNSA’s mission to maintain and modernize the nuclear stockpile through the Stockpile Stewardship and Management Program. The Office of Defense Programs is responsible for maintaining and modernizing the stockpile. Our engineers and technicians ensure the health of the weapons by studying and replacing components and materials as they age. Scientists conduct experiments using some of the most advanced facilities in the world to enhance our understanding of weapon performance. Production facilities manufacture the thousands of materials and components that comprise modern nuclear weapons, assuring their long-term reliability.' },
  { page: '/aboutus', text: 'About us: A successful transmission network requires deliberate planning, and a new and different approach. One that identifies long-term, flexible, and interregional solutions that will meet national interests. Modernizing transmission planning can provide greater certainty to drive investment to the highest-need transmission projects and enable development of the projects with the largest long-term benefit for consumers.' },
  { page: '/contactus', text: 'Contact us via email or phone.' },
  { page: '/mission', text: 'Our mission is to innovate...' },
  { page: '/new-horizons', text: 'New Horizons Deploying innovative solutions and advancing transmission systems across the country are essential to building out a better grid that achieves the U.S. Department of Energy’s (DOE) goals to meet the growing demand for electricity and provide clean, reliable, secure, and resilient power to all Americans, with emphasis on Tribal nations, rural and remote communities, disadvantaged communities, and energy transition communities. Through historic investments from the Bipartisan Infrastructure Law and Inflation Reduction Act that have allowed for stronger public-private partnerships, DOE is expanding access to affordable, reliable electricity by maintaining and investing in critical generation facilities, increasing grid resilience, and modernizing and expanding transmission and distribution systems. With our current momentum, DOE plans to expand long-distance transmission line capacity by 16% by 2030, including building 7,500 miles of new transmission lines so as to connect low-cost energy with more communities.A successful transmission network requires deliberate planning, and a new and different approach. One that identifies long-term, flexible, and interregional solutions that will meet national interests. Modernizing transmission planning can provide greater certainty to drive investment to the highest-need transmission projects and enable development of the projects with the largest long-term benefit for consumers.' },
  // add more pages and text here
];
